// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqbypmoxcvtiljwctwlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxYnlwbW94Y3Z0aWxqd2N0d2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDE2ODAsImV4cCI6MjA2Nzc3NzY4MH0.lWyeWdWcy6qpaH9kb_agp0efC2-ybjPv1_WUb-Ng0d4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});